---
application_name: QuantifyAI
business_name: QuantifyAI, LLC
business_address: |-
  123 Main Street
  San Francisco, CA 94102
domain: quantifyai.com
support_email: support@quantifyai.com
default_from_email: QuantifyAI <no-reply@quantifyai.com>
background_job_processor: sidekiq
email_provider: sendgrid
account_types: team
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
- stripe
- braintree
- paypal
multitenancy:
gems:
- acts_as_tenant
